language: java
install: ./gradlew setupDecompWorkspace
script:
  - ./gradlew check
  - ./gradlew build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  - provider: releases
    api_key:
      secure: "BLt80/Z4PLl1XxjuiiVLopxdf76lT4kHBs+Kj5epnKLuGw6WkzU/3x2IiGEZzhVf7Pp2ZUFD9sK4RtwBFdMLVhjPsuZoNQaEaXdI2faFfp63kC3yXNTrJy7qbUKpH5MqvJwgC6sTaBDmPpKiW125CGnM3n43qlEiAOor3UL3pDZZFEnf8A35/mD9LmyfGS5gel70z1S0JriNwcXAzXxwulZ4XSzWdXZGvjU9OgfthxLq5WuuS+F6WEOeUn58pZv9cpgaTJqzk9BWAOxPG6ubDCXG0OFzs5eiQp9o0wu0kJhb80PvYgLCzB2MuVFlW0oy1hBlarY/mIqAQx0OgUbOaPp5q0oCXbdgU+V9KbiaR3vwKS2cuEmjg1oTUlWO9UfDQMqgjsSlM6Rx3Tvoma7fbdQ85+lcXRr138xuiMkam7WoybqHa7b9tfRDILVoeEg84lSHASdvdrn24MUsISa5St8hIqz3w1Lh9GskzS29q5j74UA7NoMOI7CCpiJZyHQvaRLYewvhjK9yqcLpplJL8vPWZIg1bawo3HjldE3iftBWV3ZwknwrpG57PHqdzd8wjfKFr8KGNP7kIpTnXVmf8bVVRNSWaAnA7JHMRC4bD0Fm/8dznOF1ToVb0TlALBWwUv/RQBUopcRq8sCWFvfnt4f7UZDBdmXpLOPe3nr8C7c="
    file_glob: true
    file: "build/libs/*.jar"
    skip_cleanup: true
    on:
      tags: true
    draft: true
  - provider: s3
    access_key_id:
      secure: "Lc4KyfILvDfk0KMPD5LtnraGGuoK1XgEPHAN1gGniQVvDc1BVhOxesGawXrZi+118SVOtD+F/yAkrakh2rU3PTz8hPDpkLIei+4UqMbzcgKx1LY78sLhdItq6hbzrzba29gWlmxBla1Inw3WzuiKcQ6EMIy9yPe7mvz+Nx6ysqm2BhJwN55+atoylsANOTwFs3FeXn0DEycmJl/b1PWaGmDMNJ87zHLb2EPQ/ThSgW078EGFmKmVbUQ1HoBKfa8sALknY3fp7imk/UudJyP+azbnjG44nqt0o1V3c4y9LVLrjT8JFBueELKlKHe+3p4z1fMcMb5O+eaSw6RJrCPZt6kyqaNJebCFWC7NKeTlQT+FAPHYpGLsyc2D6YNM/dA1TEa5P6K0/F32auhde1ZVeDzCNO3mtfYLrUUhYHdXt7qeme4auDYvGVg/tbqrtpfoQBlDniAFrWMe9ZZWEGvmw21VfVM6mMs/k5EfwGR3Ghx9MDvLyRvZ4P9gQCjcKNKSq+JvWcxF1yAQdAPoGKbkz8WWWcIl60UCLFsQibTHQcRWlK++GXhJZx2jsHeuIUl9amQ2Lkn3fsgHs9pxsraNKHb3IMUeroxvrexjsi7hGk/dxWTK6vrUZMphdM0DbFJ2rMkeixqzpjefVe3Xb27CDIcUZJYJK4/cGf6N76b4hSA="
    secret_access_key:
      secure: "ZmO/D7UracUTmCTwro0T0vgNqfnTyK3DYn580lkfgdmQup4cKZAZouTDL2+RRpQ/ayuSWHDwY8LEaVGLsqhXoNaJlWz+cQggVjxF9ovDgvZglO1COp6zO37OOSh+Gss9Ra0MsraWgACayeSK3ue2rbfzHR60af+veaEF76y/M3VXdAaltO/Zq4LkwgjvWRa8A8XjAIk/1b8hWKNh39Fldx5Vs0TmcfYIWqKiqzcuxTvIisNFyPlhu6abFBVzHmwLusm2ueFBF4OuQLv2lvZfBQC+OULSONWMlm8b4WTbHN0/OrmVeQAw401Pusx4sCAP9iHsrkw62XPbNF8a0eAPpgctpEhCqL1Cdta7QgKUTNySF4Ehn0CbKQNe4qqVTAicaUEuMMRo2RUECFRGHHTuiJwBB9qTISMB8B8qQLDQBwvxsEeYWL90S3KZXBIjoXLmVQ26GSSlRXj6QhOZRmZI7EDh0PKrlpHjGpyTHygrEtfHBFeWSQ4RKuHK2EjJoX3LWuzGzg6V6eQ+xnD7AIsQ+cv1D1zVHeVlByY+m1qEUdMr2fekHns88T3EDj26tKIC6kuG25/dvAoUE66wuhoemocKOacthpUg9ZIaurAvtolgXTF06at78H8/Bw2MwbzEaJzxwJdL0nJc0PJStS4phna4ld9PR3ZLKSX8FvTxmQU="
    bucket: "pkmnfrk-minecraft-builds"
    skip_cleanup: true
    local_dir: build/libs
    upload-dir: "megacorp/$TRAVIS_BRANCH"